server:
  port: 8080

# datasource
spring:
    datasource:
      url: jdbc:mysql://123.56.251.13:16033/lab?serverTimezone=UTC&useAffectedRows=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: MiMaShi123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

logging:
    level:
      com.learnhow.springboot.mybatis.dao: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
debug: false
cup:
  path: D:\imageStore
